# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:273406938209:android:4dbe7a2db17be1b18e2e20",
    firebase_cli_token: "1//0953E50vCIH--CgYIARAAGAkSNwF-L9Ir6kVLYghxlVBnbnn-mEPhx2ycts7F4IyVJ5rKAov2H6otD51k7TFXByz4DiwcstwKkxI",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "abdullahahmed1991998@gmail.com, abdallamessi10000@gmail.com",
    release_notes: "Version 1.0.0"
  )
  end
end
